---
- name: Memory
  shell: "ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -4"
  register: var_output
- debug:
    var: var_output.stdout_lines
    
- name: to check swap utility  
  shell: free | grep Swap | awk '{print $3/$2 * 100}'
  register: swap_file
- debug:
    var: swap_file.stdout_lines[0]
