pipeline {
    agent any
         stages {
              stage (' Memory_usage ') { 
                  
                  steps {
                     sh 'ansible-playbook  /var/lib/jenkins/workspace/${JOB_NAME}/Memory_usage/Playbooks/Memo_usage.yml'
                     }
                     
                 }
              }
          }    
                     
         
         
  
